name: Package and Upload Firmware

on:
  push:
    branches:
      - main
    paths:
      - 'firmware/**'

jobs:
  package:
    name: Zip and Release Firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package Firmware Directory
        run: |
          zip -r VLC-ESP32-Firmware.zip firmware/rx firmware/tx_dma firmware/tx_non_dma

      - name: Upload Zip to Release
        run: |
          gh release upload latest VLC-ESP32-Firmware.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
